### ISSUE TITLE
Stitch: Unable sync 10 specific suggestion records, but works fine with the rest

### ISSUE THREAD

**Issue by danUserVoice** [singer-io/tap-uservoice#2]
I'm unable to recreate the problem; however, the API request pulls 100% of the suggestions from the UserVoice instance, ~400.

When I sync the data to Redshift, using [Stitch](https://www.stitchdata.com/docs/integrations/saas/uservoice), 10 suggestions are missing. I've re-synced, carried out historical syncs and nothing seems to remedy the issue.

There's no obvious correlation in the data either. What could be going on here?

I can provide further information upon request.

**Comment by nick-mccoy** [comment]
HI @danUserVoice, if you know the `id` of one of the missing suggestions, can you try running the tap locally and adding code to try and catch that `suggestion` record coming through?

You could modify base.py at this location:
https://github.com/singer-io/tap-uservoice/blob/a4c182e5f2df34618f8f0c75458da97208516196/tap_uservoice/streams/base.py#L117
and add something like:
```
rec = transformer.transform(rec, self.catalog['schema'], metadata.to_map(self.catalog['metadata']))
if rec['id'] == <id of known missing suggestion>:
  import pdb
  pdb.set_trace()
  LOGGER.info('Caught Missing Record!')
```

This would help us isolate the problem.  If you don't hit the breakpoint, and the suggestion is never caught, then the problem lies either in the API or the tap.  If the suggestion is caught, then the problem may be somewhere in the Stitch pipeline. 

Let me know if that makes sense.

**Comment by danUserVoice** [comment]
Thanks @nick-mccoy! I'll run some tests and get back to you with findings next week.

**Comment by danUserVoice** [comment]
Hi @nick-mccoy 

After some debugging, we received the following error:
`ERROR Errors during transform body: None does not match {'type': 'string'}`

This was encountered when syncing Suggestions. A suggestion body can be `null` in UserVoice, and the Suggestion should still sync.

Could you update the catalog.json, please?

**Comment by shdunning** [comment]
@nick-mccoy i think this will address the issue @danUserVoice and I found earlier: https://github.com/singer-io/tap-uservoice/pull/3

**Comment by nick-mccoy** [comment]
👍 I merged and deployed this change.  Let me know if that fixes the error.

**Comment by shdunning** [comment]
@nick-mccoy that seems to fix it in our testing env - wait until @danUserVoice confirms that the main issue is addressed in prod plz before closing this out. thanks!

**Comment by danUserVoice** [comment]
@nick-mccoy I have verified the data now matches up, post fix. Everything looks good, and 100% of the Suggestions from the UserVoice instance were successfully synced to Redshift!

Really appreciate your guidance on this one. Thanks!
