### ISSUE TITLE
write access to this repo?

### ISSUE THREAD

**Issue by shdunning** [singer-io/tap-uservoice#6]
Hey @nick-mccoy, what do you think about granting me write-access to this repo? It would be helpful for us going forward if we could push out quick bug fixes.

Thanks in advance!

**Comment by nick-mccoy** [comment]
Hey @shdunning -- If you are hoping to push quick bug fixes to the tap-uservoice running in Stitch, we have a separate deploy process to push changes to Stitch, so gaining write access to this repo wouldn't do you a whole lot of good.  

Otherwise, you are free to fork this repo and push changes to a separate pypi repo if you are looking to get bug fixes out to folks running this locally.  

As always, we'll do our best to respond to issues and PRs on this repo and get changes/fixes pushed to Stitch.
